In [8]:
import cv2
import numpy as np
import math

In [3]:
cv2.namedWindow('window',cv2.WINDOW_NORMAL)
pic=cv2.imread('../material/used/images/smile_face.png',1)
cv2.resizeWindow('window',(pic.shape[1],pic.shape[0]))
cv2.imshow('window',pic)

while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()
        

In [ ]:
'''
清晰度包括：亮度、对比度、尺寸大小、细微层次、颜色饱和度
对比度=最大亮度/最小亮度


'''

In [16]:
print(pic.shape)

(344, 693, 3)


In [17]:
print(pic[10,50,1])

255


In [5]:
pic_1=pic[100:300,200:300]
cv2.imshow('window',pic_1)
while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()

In [8]:
pic_1=pic[:,:341]
pic_2=pic[:,341:]

cv2.imshow('pic_1',pic_1)
cv2.imshow('pic_2',pic_2)
while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()

cv2.imwrite('../material/saved/pic_1.png',pic_1)
cv2.imwrite('../material/saved/pic_2.png',pic_2)




True

In [6]:
pic=cv2.imread('../material/used/images/red.png')
cv2.imshow('red',pic)
print('B:',str(pic[1,1,0]),'  G:'+str(pic[1,1,1]),'  R:',str(pic[1,1,2]))
while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()

B: 0   G:0   R: 255


In [7]:
b,g,r,=cv2.split(pic)
print(b,g,r)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [18]:
pic=cv2.imread('../material/used/images/smile_face.png',1)
pic_1=pic[:,:341]
pic_2=pic[:,341:]
#pic_1_r=pic_1[:,:,1]
#cv2.imshow('b',pic_1[:,:,0])
#cv2.imshow('g',pic_1[:,:,1])
cv2.imshow('r',pic_1[:,:,2])

while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()

In [3]:
pic=cv2.imread('../material/used/images/shenzhen_gray.bmp',0)
pic[pic>180]=0
pic[pic<60]=0
pic[pic!=0]=255
cv2.imshow('pic',pic)

while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()


In [6]:
pic_1=cv2.imread('../material/used/images/shenzhen_mask.bmp',0)
pic=cv2.imread('../material/used/images/shenzhen_gray.bmp',0)
pic_m=cv2.bitwise_or(pic,pic_1)
cv2.imshow('pic_m',pic_m)

while cv2.waitKey(0)!=ord('q'):
    None
cv2.destroyAllWindows()

In [10]:
pic_2=math.(1+math.exp(-1*0.04*pic))-0.5

TypeError: only size-1 arrays can be converted to Python scalars